logging:
  logs_dir: "./logs"

input_file:
  products_data_path: "./assets/products.csv"
  offers_data_path: "./assets/offers.csv"
  cleaned_products_data_path: "./assets/cleaned_products.csv"

output_file:
  cleaned_products_data_path: "./assets/cleaned_products.csv"

weaviate:
  collection_name: "Product"

embedding:
  model_name: "all-MiniLM-L6-v2"

mistral:
  api_key: "your_mistral_api_key"
  model: "mistral-large-latest"

database:
  name: "./database/offers_database.db"
