logging:
  logs_dir: "./logs"

input_file:
  products_data_path: "./assets/products.csv"
  offers_data_path: "./assets/offers.csv"
  cleaned_products_data_path: "./assets/cleaned_products.csv"

output_file:
  cleaned_products_data_path: "./assets/cleaned_products.csv"

weaviate:
  collection_name: "Product"

embedding:
  model_name: "all-MiniLM-L6-v2"
  model_type: "sentencetransformer"

llm:
  provider: "gemini" # openai - mixtral-8x7b-32768 - llama3-70b-8192 - gemma-7b-it - mistral
  temperature: 0.0

google:
  api_key: "AIzaSyCNd9IJQ7_n_CuwFDoJ_pspYEJ024hZ28U"

openai:
  api_key: ""

groq:
  api_key: "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"

mistral:
  api_key: "XxcQ9HViJPZbUM7wdEsRU37HISMkyv2j"
  model: "mistral-large-latest"

database:
  name: "./database/offers_database.db"
